version: '3'

services:

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017/myapp
      - NODE_ENV=production
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
